feat(elements|ino-nav-drawer): implement mobile nav-drawer
inovex/elements pull request #1035
Opened 2023-08-03 12:23 UTC by TobiasHeimGalindo

Closes #1010

2023-08-17 13:50 UTC, MariaLStefan requested changes
Nicely done 👌
Just some optimizations

2023-08-17 13:50 UTC, MariaLStefan commented on packages/elements/src/components/ino-nav-drawer/ino-nav-drawer.tsx
> +  }
You can use stencils `@Watch()` annotation to detect changes in `isMobile`. This function can then set the variant depending on the `isMobile` content.

```
  @Watch('isMobile')
  handleIsMobileChange() {
    if (this.isMobile) {
      this.variant = 'modal';
    }
  }
````
Further down the line, you only have to check `this.variant` to get according css classes

2023-08-17 13:50 UTC, MariaLStefan commented on packages/elements/src/components/ino-nav-drawer/ino-nav-drawer.scss
> +    clip: rect(1px, 1px, 1px, 1px);
clip is deprecated https://developer.mozilla.org/en-US/docs/Web/CSS/clip
We should use the newer [clip-path](https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path)

2023-09-12 13:49 UTC, janivo requested changes

2023-09-12 13:49 UTC, janivo commented on packages/elements/src/components/ino-nav-drawer/ino-nav-drawer.tsx
> +  }
What's the need for changing the `variant` property? As far as I can see the `variant` prop only applies different classes in the `render` method. The same can be achieved by also adding the classes when the `isMobile` class is set. 

The fact that the `isMobile` makes the `variant` prop obsolete when it is set to `true` might also be an indicator that the mobile view is just another `variant`. What do you think about adding `mobile` as another variant?

2023-09-12 13:49 UTC, janivo commented on packages/elements/src/components/ino-nav-drawer/ino-nav-drawer.tsx
> +  }
When transitioning from the mobile view to the desktop view, we also need to remove these classes again. That's currently not done, right?

It's probably a good idea to separate all the logic thats mobile specific into two methods like `activateMobileMode`and `deactivateMobileMode` or something like that.

2023-09-28 15:35 UTC, janivo approved these changes

2023-09-28 15:36 UTC, merged