feat(elements): improve patterns-playground dx
inovex/elements pull request #1145
Opened 2023-12-21 11:28 UTC by TobiasHeimGalindo

Closes #1108

2024-01-29 11:58 UTC, BenPag requested changes
From my side everything looks good. Please reslove the merge confict.

2024-01-31 14:51 UTC, janivo requested changes
Really cool, thank you for writing a guide ⭐

2024-01-31 14:51 UTC, janivo commented on packages/landingpage/utils/routes.tsx
> -  // 'anotherMainRoute': ['subroute1', 'subroute2']
I think we need some more patterns (and also functionality in #1165) to release it to the public, so we might want to keep it disabled for now

2024-02-01 11:26 UTC, janivo approved these changes

2024-02-01 13:03 UTC, merged