fix(elements-angular): make ng-add work with newer angular versions
inovex/elements pull request #1149
Opened 2023-12-22 16:59 UTC by janivo

2024-01-09 10:38 UTC, BenPag requested changes
How do you tested it? I tried it with yalc but i got some compilation errors.

![image](https://github.com/inovex/elements/assets/23154336/4b38e753-87f0-4b6a-816a-8eb6de89867c)

But the ng-add command seems to be working

2024-01-09 15:00 UTC, janivo commented
> How do you tested it? I tried it with yalc but i got some compilation errors.
> 
> ![image](https://private-user-images.githubusercontent.com/23154336/295179619-4b38e753-87f0-4b6a-816a-8eb6de89867c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MTIzODUsIm5iZiI6MTcwNDgxMjA4NSwicGF0aCI6Ii8yMzE1NDMzNi8yOTUxNzk2MTktNGIzOGU3NTMtODdmMC00YjZhLTgxNmEtOGViNmRlODk4NjdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDE0NTQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2Y2I3M2M5NDk5YTZjZDQ3Y2Y1ODVlM2FhOWU3YjE4MmQ2NDNmNjBmYTZiYjZkZTZkZmM1OTBkMDljMmY5MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SRSYPOjv6FqrDtacP9lovESzd1p93naSJl1h-JEWeNc)
> 
> But the ng-add command seems to be working

I tested it by building it locally, moving it to another independent angular application and running `ng add <path to build tar>`. Afterwards, to make it runnable you've got to replace the `inovex.de/elements` version in the `node_modules` of the independent by hand with a build of the same branch. Kinda complicated but I was able to test it successfully 😅

2024-01-11 09:28 UTC, BenPag commented on packages/elements-angular/src/schematics/utils/ast.ts
> +  const metadataChange = addSymbolToNgModuleMetadata(moduleSource, modulePath, 'imports', 'InoElementsModule.forRoot()');
In my example project only the InoElementsModule will be added to the import list. The necessary `InoElementsModule.forRoot()` statement was not added in the @NgModule imports array.

2024-01-22 09:28 UTC, BenPag approved these changes

2024-01-22 09:53 UTC, merged