style(elements|ino-input): add padding to label
inovex/elements pull request #1189
Opened 2024-01-22 18:25 UTC by MariaLStefan

Closes #1164 

## Proposed Changes

- fixes truncating label on `ino-input`

## showcase

https://github.com/inovex/elements/assets/103122411/4bb9aba1-56fc-4ff1-9f9b-4676a0a8fdd5

2024-02-01 08:46 UTC, janivo requested changes

2024-02-01 08:46 UTC, janivo commented on packages/elements/src/components/ino-input/ino-input.scss
> +  & .mdc-floating-label:not(.mdc-floating-label--float-above) {
Does not seem to be fixed quite yet:

![image](https://github.com/inovex/elements/assets/22963121/abca8f4e-730c-4375-82c3-ee5bca47e6d4)

These changes seem to have no effect when the label is floating above.

2024-03-13 10:55 UTC, janivo requested changes
Seems like it still not quite right. In the storybook:

![image](https://github.com/inovex/elements/assets/22963121/59213b60-6bbb-430f-9034-529a6a8e6140)

2024-03-13 11:40 UTC, BenPag commented
> Seems like it still not quite right. In the storybook:
> 
> ![image](https://private-user-images.githubusercontent.com/22963121/312423901-59213b60-6bbb-430f-9034-529a6a8e6140.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMjkxNjIsIm5iZiI6MTcxMDMyODg2MiwicGF0aCI6Ii8yMjk2MzEyMS8zMTI0MjM5MDEtNTkyMTNiNjAtNmJiYi00MzBmLTkwMzQtNTI5YTZhOGU2MTQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDExMjEwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmNWJmZDAwYjI1YTNkOTFjOWY1OGY2ZGQyZThiZTUyOTNmNDA2MjA0NWJhYWZiZjI4NjI1YTc5M2U2MDlkZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dLRGluJQdGf93vHOFH5X9J4ImNth3luGAXJgHumVkgc)

To late yesterday... I fogot to adjust some parameters for optimal spacing...

2024-03-13 13:13 UTC, janivo commented
@BenPag still the same 🤔 
![image](https://github.com/inovex/elements/assets/22963121/ef70e201-b62b-4214-9d8d-6a40bbcc74db)

2024-03-14 14:03 UTC, janivo approved these changes

2024-03-14 14:04 UTC, merged