refactor(elements/ino-fab): migrate stencil e2e tests to spec test
inovex/elements pull request #1278
Opened 2024-02-26 09:44 UTC by BenPag

Part of #1258

## Proposed Changes

- migrate tests to playwright
- split test up into playwright and jest unit tests
- disable shadow down for `ino-fab` and `ino-fab-set`

2024-03-14 08:11 UTC, janivo requested changes

2024-03-14 08:11 UTC, janivo commented
Is there a specific reason, why you disabled the shadow dom?

2024-03-14 08:29 UTC, BenPag commented
> Is there a specific reason, why you disabled the shadow dom?

With shadow dom i was not able to test the components in jest.

2024-03-15 17:00 UTC, janivo approved these changes

2024-03-15 17:00 UTC, merged