fix(elements|ino-datepicker): fix validation if no value is provided
inovex/elements pull request #141
Opened 2020-10-15 13:00 UTC by Sl1nd

2020-10-16 07:50 UTC, janivo requested changes

2020-10-16 07:50 UTC, janivo commented on packages/elements/src/components/ino-datepicker/ino-datepicker.tsx
> +    console.log(this.isInValid);
Could you remove this log out?

2020-10-16 07:50 UTC, janivo commented on packages/elements/src/components/ino-datepicker/ino-datepicker.tsx
> +      if(value) this.isInValid = true;
We should provide some test cases to confirm that this works as intended

2020-11-07 08:35 UTC, pfecht commented
@Sl1nd @janivo Any progress? Stumbled across this as well

2020-11-10 14:44 UTC, janivo approved these changes

2020-11-10 14:47 UTC, merged