refactor(elements): use stencil listener
inovex/elements pull request #307
Opened 2021-03-12 10:24 UTC by P1NHE4D

⚙️ **Changes:**
* Removed the event listeners from the `ino-dialog` component since the events were never dispatched due to the missing `data-mdc-dialog-action` attribute (see [mdc-dialog documentation](https://github.com/material-components/material-components-web/tree/master/packages/mdc-dialog#full-screen-dialog))
* Added stencil's `Listen()` decorator to the `ino-tab` and `ino-tab-bar` components

⚠️ **The `Listen()` decorator can not be used in the following components:**
| Component | Reason |
| ----------- | -------- |
| `ino-nav-drawer` | Event listener is attached to a specific target. The only targets supported by `Listen()` are `window`, `document`, and `body`. |
| `ino-chip-set` | Event listener is only attached in specific cases. |
| `ino-datepicker` | Event listener is attached to a specific target. |
| `ino-file-input` | Listens to multiple events at the same time. What is more, some events are only attached if they're supported by the browser. |
| `ino-radio-group` | Listeners are attached to specific targets. |
| `ino-segment-button` | Listeners are only attached if the segment button belongs to a group. |
| `ino-tooltip` | Listeners are attached to specific targets. |

2021-04-19 10:22 UTC, janivo requested changes
Just a really small change

2021-04-19 10:22 UTC, janivo commented on packages/elements/src/components/ino-tab-bar/ino-tab-bar.tsx
> +} from "@stencil/core";
The `'...'` should stay

2021-04-21 15:24 UTC, P1NHE4D commented on packages/elements/src/components/ino-tab-bar/ino-tab-bar.tsx
> +} from "@stencil/core";
fixed ✅

2021-04-22 10:29 UTC, janivo approved these changes

2021-04-22 10:30 UTC, merged