refactor(elements): replace attribute selectors
inovex/elements pull request #309
Opened 2021-03-24 14:29 UTC by janivo

Closes #243

## Proposed Changes

- Replaces all attribute selectors
- Some small improvements to the storybook

2021-03-31 09:03 UTC, P1NHE4D requested changes

2021-04-09 07:29 UTC, P1NHE4D commented
@janivo Could you resolve the conflicts? 🙂

2021-04-12 08:30 UTC, janivo commented
@P1NHE4D: thanks for the heads up. I rebased it. Only things that I had to resolve were the `ino-popover` and `ino-tooltip`.

2021-04-21 17:12 UTC, P1NHE4D approved these changes

2021-04-21 17:13 UTC, merged