feat(elements|ino-select): add slot for icon
inovex/elements pull request #317
Opened 2021-04-02 10:31 UTC by P1NHE4D

✨ **Features:**
* added `ino-icon-leading` slot to `ino-select` component

🎟️ **Closes #233**

2021-04-19 10:30 UTC, janivo requested changes
![image](https://user-images.githubusercontent.com/22963121/115222217-c8783c80-a10a-11eb-970b-fb4249809175.png)
The Icon seems kinda huge. We should use the same styles applied in the `ino-input` component. Maybe we can extract similar styles in a mixin? We could create a `mixin.scss` in `/base` and use those mixin in both components.

2021-04-21 16:53 UTC, P1NHE4D commented
> ![image](https://user-images.githubusercontent.com/22963121/115222217-c8783c80-a10a-11eb-970b-fb4249809175.png)
> The Icon seems kinda huge. We should use the same styles applied in the `ino-input` component. Maybe we can extract similar styles in a mixin? We could create a `mixin.scss` in `/base` and use those mixin in both components.

I initially made the icon smaller, but it looked a bit odd next to the rather big drop-down selector, especially with a floating label.

2021-07-15 07:53 UTC, janivo requested changes
I added a story as an example and noticed that the label is not positioned properly yet:
![image](https://user-images.githubusercontent.com/22963121/125750687-c193f544-d6fc-428c-9c74-df88a1998a9f.png)

2021-08-03 08:57 UTC, janivo approved these changes

2021-08-03 09:27 UTC, merged