fix(elements|ino-list-item): fix checkbox positioning
inovex/elements pull request #335
Opened 2021-04-07 08:03 UTC by P1NHE4D

⚙️ **Changes:**
* Fixed positioning of the checkbox in `ino-list-item` component

🎟️ **Closes #276**

2021-04-19 08:44 UTC, janivo requested changes
The `flex-start` seems to have an impact on the icons in the list (see below). Could you try to align them (checkbox, radio-button, icon) correctly?

Before:
![image](https://user-images.githubusercontent.com/22963121/115207454-e8543400-a0fb-11eb-9cbd-3e3cba5010c6.png)

Now:
![image](https://user-images.githubusercontent.com/22963121/115207600-0a4db680-a0fc-11eb-9400-fc587439d97b.png)

2021-04-21 16:18 UTC, P1NHE4D commented
> The `flex-start` seems to have an impact on the icons in the list (see below). Could you try to align them (checkbox, radio-button, icon) correctly?
> 
> Before:
> ![image](https://user-images.githubusercontent.com/22963121/115207454-e8543400-a0fb-11eb-9cbd-3e3cba5010c6.png)
> 
> Now:
> ![image](https://user-images.githubusercontent.com/22963121/115207600-0a4db680-a0fc-11eb-9400-fc587439d97b.png)

Thank you I did not notice that. Should work now. 👍

2021-04-22 10:28 UTC, janivo commented
Still doesn't look quite right:
![image](https://user-images.githubusercontent.com/22963121/115699543-03c27780-a366-11eb-809f-348f49ec8923.png)

The leading graphics should all be aligned in one "column" just like the trailing ones.

2021-07-15 07:34 UTC, janivo approved these changes

2021-07-15 07:35 UTC, merged