WIP: feat(elements|ino-select): add error property
inovex/elements pull request #424
Opened 2021-09-13 09:18 UTC by janivo

Relates to #423

## Proposed Changes

- add Property `error` to enable error state programmatically

2021-09-13 09:20 UTC, janivo commented
Currently the form submission is not prevented if there is no value selected and `required` set ⚠️

2021-09-16 11:23 UTC, BenPag requested changes

2021-09-16 11:23 UTC, BenPag commented on packages/storybook/custom-elements.json
> -        }
This CSS property is used in styles.

2021-09-27 09:55 UTC, janivo commented on packages/storybook/custom-elements.json
> -        }
Whops, these got deleted by accident.

2021-09-27 10:48 UTC, BenPag approved these changes

2021-09-27 11:01 UTC, merged