feat: add onSlideChanged event to ino-carousel
inovex/elements pull request #650
Opened 2022-06-16 12:01 UTC by TobiasHeimGalindo

As the value changes upon clicking the directional icon buttons the current slide value gets emitted.

2022-06-20 11:37 UTC, BenPag requested changes

2022-06-20 11:37 UTC, BenPag commented on packages/elements/src/components/ino-carousel/ino-carousel.tsx
> +      this.valueChange.emit(allSlides[0].value);
Please check if `allSlides[0]` is `null `or `undefined`

2022-06-20 11:37 UTC, BenPag commented on packages/elements/src/components/ino-carousel/ino-carousel.tsx
> +          allSlides[allSlides.length - 1];
To be sure, check if the array is not empty.

2022-06-20 11:37 UTC, BenPag commented on packages/elements/src/components/ino-carousel/ino-carousel.e2e.ts
> +describe('InoRadioGroup', () => {
Naming is incorrect i guess

2022-07-08 15:13 UTC, janivo requested changes
Nice job overall! 💥 
After you've applied the suggestions, run `yarn build` once again and commit the generated stuff, because we've made changes to the documentation.

2022-07-08 15:13 UTC, janivo commented on packages/elements/src/components/ino-carousel/ino-carousel.tsx
> +        }
We've confirmed that all slides is not empty
```suggestion
	      nextSlide =
	        (carouselSlide.previousElementSibling as HTMLInoCarouselSlideElement) ??
	        allSlides[allSlides.length - 1];
```

2022-07-08 15:13 UTC, janivo commented on packages/elements/src/components/ino-carousel/ino-carousel.tsx
> +   * Emits the value of the slide once it changed
The slides have not been changed on arrow press. We inform the consumer that the slide should be changed.
```suggestion
   * Emits the `value` of the slide that should be displayed after the left or right arrow has been clicked.
```

2022-07-12 06:42 UTC, janivo commented on packages/elements/src/components/ino-carousel/ino-carousel.tsx
> +    const carouselSlide = this.getSlides()[this.currentSlide];
```suggestion
    const allSlides = this.getSlides();
    
    if (!allSlides || allSlides.length === 0) return;
    
    const carouselSlide = allSlides[this.currentSlide];
```

2022-07-12 06:45 UTC, janivo commented on packages/elements/src/components/ino-carousel/ino-carousel.tsx
> +    const carouselSlide = this.getSlides()[this.currentSlide];
```suggestion
    const allSlides = this.getSlides();
    
    if (!allSlides || allSlides.length === 0) return;
    
    const carouselSlide = this.getSlides()[this.currentSlide];
```

2022-07-12 07:52 UTC, merged