chore: create basic setup for new landingpage
inovex/elements pull request #765
Opened 2022-10-14 15:03 UTC by janivo

closes #757

2022-10-21 13:37 UTC, MariaLStefan requested changes
Looks great! Thanks for setting up the new landingpage :) I only found some minor things that could be adjusted.

2022-10-24 14:01 UTC, janivo commented on packages/landingpage-new/styles/Home.module.css
> +}
These were some leftovers of the initial app created by next. I removed them for clarity

2022-10-24 15:27 UTC, janivo commented on packages/landingpage-new/components/layout/header.module.scss
> +}
nice idea!

2022-10-24 15:28 UTC, janivo commented on packages/landingpage-new/components/layout.tsx
> +import Footer from "./layout/footer";
Good spot. I added an ESLint Rule to make sure

2022-10-24 15:38 UTC, merged