feat(landingpage): finish about page
inovex/elements pull request #819
Opened 2022-12-12 12:49 UTC by ninaschlz

Closes #810 

## Proposed Changes

- Contributors: Add designers to list and a role to each contributor
- History: Describe history of inovex elements
- Activity: Graph with repo contributions the last 12 months

2022-12-12 17:16 UTC, janivo requested changes
Great job overall. Looks very nice! Also nice, that you found a way to include our designers 👍🏼 
There are just some technical aspects I would like to change

2022-12-12 17:16 UTC, janivo commented on packages/landingpage-new/components/about/activity.tsx
> +const months: string[] = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
Can we used the short names here to reduce noise? `Jan 22`, `Feb 22`, ...

2022-12-14 11:38 UTC, janivo requested changes
When navigating away and to the about page, this error appears:
![image](https://user-images.githubusercontent.com/22963121/207585287-ac66e713-3444-40b2-b361-0b9eaf2ad733.png)

2022-12-14 11:38 UTC, janivo commented on packages/landingpage-new/components/about/activity.tsx
>        ],
Can we move this to the `useEffect` hook above? That way, the `label` and `contributions`  will be unnecessary and all of our data lies in `graphData`

2022-12-16 08:30 UTC, janivo requested changes
![image](https://user-images.githubusercontent.com/22963121/208056522-4252a043-2246-4726-9627-c7192846cee4.png)

The activity graph appears to be empty when running `yarn build` and `yarn start` 🤔

2022-12-16 10:16 UTC, ninaschlz commented
> ![image](https://user-images.githubusercontent.com/22963121/208056522-4252a043-2246-4726-9627-c7192846cee4.png)
> 
> The activity graph appears to be empty when running `yarn build` and `yarn start` 🤔

Strange... I can't reproduce this. In my case all data are present

2022-12-16 15:00 UTC, janivo approved these changes

2022-12-19 08:15 UTC, janivo approved these changes

2022-12-19 08:16 UTC, merged