refactor(landingpage): update inovex-logo in footer
inovex/elements pull request #931
Opened 2023-04-19 16:43 UTC by MariaLStefan

Closes #922

2023-04-20 13:40 UTC, BingeCode submitted a review, later dismissed

2023-04-21 12:22 UTC, janivo requested changes

2023-04-21 12:22 UTC, janivo commented on packages/landingpage-new/public/inovex-logo.svg
We will need this logo for our new README at the root level of our project as well. Could you place the new logo [here](https://github.com/inovex/elements/tree/master/assets)? It should be copied to the landingpage assets automatically because of our [copy plugin in our next config](https://github.com/inovex/elements/blob/a5910b681ff656fdd7a0dac15d2bad1672436ab8/packages/landingpage-new/next.config.mjs#L32-L47).

2023-04-25 13:36 UTC, janivo approved these changes

2023-04-25 13:36 UTC, merged