refactor(README): Improve README.md (#919)
inovex/elements pull request #946
Opened 2023-05-09 11:04 UTC by BingeCode

Closes #919 

Showcase and Demo need to be added in later PR.

2023-05-09 15:01 UTC, janivo requested changes

2023-05-09 15:01 UTC, janivo commented on scripts/getContributors.js
Instead of using Puppeteer, we can use the API of Github directly. Have a look at this function: https://github.com/inovex/elements/blob/4e4be6b8a7167afe3272beb7c37493fb0cb77424/packages/landingpage-new/pages/%5Blang%5D/about/index.tsx#L25

2023-05-09 20:54 UTC, BingeCode commented on scripts/getContributors.js
This is just a quick helper function that I wrote to extract the contributors from the repo. I used it in a separate repo to extract the image urls and profile names. I just saved it here so that it can be used manually in the future in case the contributor section needs to be updated. Although this can be done manually in the future since it isn't a lot of work to add a few contributors manually. We don't _really_ need it in the repo but I thought it might come in handy when you want to update a bulk of new contributors. Let me know how you want this to be managed.

2023-05-31 14:46 UTC, janivo submitted a review, later dismissed

2023-05-31 14:53 UTC, janivo approved these changes

2023-05-31 14:58 UTC, merged