refactor(elements|ino-tooltip): implement new design
inovex/elements pull request #975
Opened 2023-06-12 17:07 UTC by MariaLStefan

Closes #957

2023-09-12 04:22 UTC, Sl1nd commented
@MariaLStefan Looks very good! The only improvement would be to align the preselected colorScheme values of storybook playgrounds of tooltip and popover. For InoPopover currently "light" is preselected. InoTooltip's playground sample uses "primary" colorScheme. At this consumers could assume a different color schmes of tooltips and popovers on first look.

2023-09-12 04:23 UTC, Sl1nd approved these changes

2023-09-12 13:31 UTC, janivo requested changes
There are some conflicts that need to be resolved

2023-09-12 13:31 UTC, janivo commented on packages/elements/src/components/ino-tooltip/ino-tooltip.tsx
> +                {this.headerText && <header>{this.headerText}</header>}
IMO the `header` should be independent of the existence of `label`.

Rougly like this:
```jsx
{header && <header> ... </header>}
{this.label ?? <slot />}
```

2023-10-26 10:16 UTC, janivo approved these changes

2023-10-26 10:21 UTC, merged