refactor(storybook): use new stylesheet for storybook
inovex/elements pull request #991
Opened 2023-06-26 14:39 UTC by MariaLStefan

Closes #965

## Proposed Changes

- add & use new color theme in storybook

2023-06-29 13:27 UTC, BingeCode commented on packages/storybook/config/manager-head.html
> +    color: var(--inovex-elements-n-3);
Why did you pick n-3 over the previous n-6? It's quite a light contrast to the background. I think n-6 would be better, perhaps even higher - for accessibility and general readability.

n-3:
<img width="76" alt="image" src="https://github.com/inovex/elements/assets/48513535/d1698eb5-ae24-4872-acbd-d6125c0f2b32">

n-6:
<img width="49" alt="image" src="https://github.com/inovex/elements/assets/48513535/492b11c3-c457-4e60-9b2c-0097743aa89c">

2023-06-29 13:28 UTC, BingeCode commented on packages/storybook/config/manager-head.html
> +    background-color: rgb(var(--inovex-elements-n-3)) !important;
Overriding styles with !important is always risky. It makes it difficult to override this style at a later point. Is there really no way to reach higher rule specifity with css selectors / import ordering?

2023-06-29 13:40 UTC, BingeCode requested changes
Looks good overall, just needs a minor readability fix and perhaps another change.

2023-09-01 15:42 UTC, janivo approved these changes

2023-09-01 15:42 UTC, merged